#!/bin/bash

accNoWanted=$1; shift

# Horrid one-liner to find account number
function accNo() {
   aws "$@" ec2 describe-security-groups 2> /dev/null | jq -r '.SecurityGroups[0].OwnerId' 
   if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
     echo "Unable to check $2" >> /dev/stderr
   fi
}

for s in $(cat ~/.aws/credentials | grep '^\[' | sed 's/[][]//g'); do 
   if [[ "$(accNo --profile $s "$@")" == "$accNoWanted" ]]; then
     echo "$s" && exit 0
   fi
done

echo "None of your account stanzas match $accNoWanted" >> /dev/stderr
exit 1

